version: '2.2'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - frontend
    image: kamal016/backend
  frontend:
    build: ./frontend
    ports:
      - '8000:3000'
    image: kamal016/frontend

  
